workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: 9b6f8519-694d-48a5-8b90-cd6c1debe0d3
        APP_STORE_CONNECT_KEY_IDENTIFIER: 6Y8XL8Q783
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_IDENTIFIER: "com.joinmeister.silentprintbrowser"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing and keychain
        script: |
          echo "Setting up manual code signing..."
          echo "Current directory: $(pwd)"
          ls -la
          
          # Clean up any existing certificates and profiles
          echo "Cleaning up existing certificates and profiles..."
          rm -rf /Users/builder/Library/MobileDevice/Certificates/*
          rm -rf /Users/builder/Library/MobileDevice/Provisioning\ Profiles/*
          rm -rf /Users/builder/Library/codemagic-cli-tools/keychains/*
          
          # Initialize keychain
          echo "Initializing keychain..."
          keychain initialize
          
          # Fetch signing files manually
          echo "Fetching signing files..."
          app-store-connect fetch-signing-files $BUNDLE_IDENTIFIER \
            --delete-stale-profiles \
            --create \
            --type IOS_APP_STORE \
            --platform IOS \
            --issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --private-key $APP_STORE_CONNECT_PRIVATE_KEY
          
          # Add certificates to keychain
          echo "Adding certificates to keychain..."
          keychain add-certificates
          
          echo "Manual code signing setup complete"
          
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
          
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email
        notify:
          success: true
          failure: true



