workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.joinmeister.silentprintbrowser
      vars:
        APP_STORE_CONNECT_ISSUER_ID: 9b6f8519-694d-48a5-8b90-cd6c1debe0d3
        APP_STORE_CONNECT_KEY_IDENTIFIER: 6Y8XL8Q783
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up build environment
        script: |
          echo "Build environment setup"
          echo "Current directory: $(pwd)"
          ls -la
          echo "Code signing will be handled automatically by Codemagic"
          
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
          echo "Flutter dependencies installed"
          echo "Checking generated files..."
          ls -la ios/Flutter/
          
      - name: Install CocoaPods dependencies
        script: |
          echo "Checking Flutter generated files..."
          ls -la ios/Flutter/
          
          echo "Installing CocoaPods dependencies..."
          cd ios && pod install
          
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
    publishing:
      email:
        recipients:
          - your-email@example.com  # Replace with your email
        notify:
          success: true
          failure: true



