workflows:
  ios_app_store:
    name: iOS App Store
    environment:
      flutter: stable
      vars:
        # === CHANGE THIS ===
        APP_DIR: "."                        # Flutter project is in root directory
        BUNDLE_ID: "com.joinmeister.silentprintbrowser"
        ASC_ISSUER_ID: "9b6f8519-694d-48a5-8b90-cd6c1debe0d3"
        ASC_KEY_ID: "6Y8XL8Q783"
        TEAM_ID: "YOUR_TEAM_ID"            # (optional) your Apple dev team id
      groups:
        - apple_signing
    cache:
      cache_paths:
        - ~/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $HOME/Library/Developer/Xcode/DerivedData
    scripts:
      - name: Diagnose repo layout
        script: |
          echo "=== Repository Structure ==="
          echo "CM_CLONE_DIR=$CM_CLONE_DIR"
          echo "Root directory contents:"
          ls -la "$CM_CLONE_DIR"
          echo ""
          echo "Checking for pubspec.yaml in root:"
          test -f "$CM_CLONE_DIR/pubspec.yaml" && echo "✅ Found pubspec.yaml" || echo "❌ pubspec.yaml not found"

      - name: Install Flutter dependencies
        script: |
          cd "$CM_CLONE_DIR"
          echo "Working directory: $(pwd)"
          
          if [ ! -f "pubspec.yaml" ]; then
            echo "❌ pubspec.yaml not found"
            ls -la
            exit 1
          fi
          
          echo "✅ Found pubspec.yaml"
          flutter pub get

      - name: Fetch iOS signing files (App Store)
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --create --type IOS_APP_STORE --platform IOS \
            --issuer-id "$ASC_ISSUER_ID" \
            --key-id "$ASC_KEY_ID" \
            --private-key @env:AUTH_KEY \
            --certificate-key @env:CERTIFICATE_KEY \
            --delete-stale-profiles

      - name: Initialize keychain & import certs
        script: |
          keychain initialize
          keychain add-certificates

      - name: Install CocoaPods (if present)
        script: |
          cd "$CM_CLONE_DIR/ios"
          if [ -f "Podfile" ]; then
            gem install cocoapods --no-document || true
            pod repo update || true
            pod install
          else
            echo "No Podfile; skipping pods"
          fi

      - name: Build IPA (Flutter)
        script: |
          cd "$CM_CLONE_DIR"
          flutter build ipa --release

    artifacts:
      - build/ios/**/*.ipa
      - build/ios/**/*.dSYM
      - build/ios/archive/**/*.xcarchive

    publishing:
      email:
        recipients:
          - info@alimhanna.com
        notify:
          success: true
          failure: true